# Generated by Django 3.2 on 2022-04-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_options'),
        ('profiles', '0002_savedmarket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedMarket',
            new_name='SavedMarketList',
        ),
    ]
