# Generated by Django 3.2 on 2022-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name_plural': 'Counties'},
        ),
    ]
