# Generated by Django 3.2 on 2022-04-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_remove_market_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='county',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='markets.county'),
            preserve_default=False,
        ),
    ]
